### ISSUE TITLE
Possible to create wallet.dat?

### ISSUE THREAD

**Issue by mattvb91** [andkom/php-bitcoin-wallet#1]
As there is both decrypt & encrypt in the sources files im assuming this library can both read & create new wallet.dat files?

**Comment by andkom** [comment]
it's only reader

**Comment by mattvb91** [comment]
Ah ok thanks. Any plans on adding it in future versions?

**Comment by andkom** [comment]
> Ah ok thanks. Any plans on adding it in future versions?

No :(
